#!/usr/bin/env python3
"""
Generates antibot_schemas_gen.go from browser_protocol.json.

Usage:
    python3 gen_antibot_schemas.py /path/to/browser_protocol.json > antibot_schemas_gen.go

This reads the Antibot domain from the CDP protocol definition and generates
Go code with MCP tool schema overrides for each command.
"""

import json
import sys

# Commands exposed via WebMCP (subset of Antibot commands)
WEBMCP_COMMANDS = {
    "fill", "clickOn", "typeText", "pressKey", "scroll", "hover",
    "selectOption", "waitForElement", "isElementVisible", "locateElement",
    "locateElementAcrossFrames", "moveTo", "dragAndDrop", "clickAndHold",
    "clickAndSlide", "getFrames", "getMousePosition", "showCursor",
}

# Map CDP types to JSON Schema types
TYPE_MAP = {
    "string": "string",
    "integer": "integer",
    "number": "number",
    "boolean": "boolean",
}


def ref_to_schema(ref, types_by_id):
    """Convert a $ref to a JSON Schema snippet."""
    if ref == "Selector":
        return "selectorSchema"
    if ref == "Coordinate":
        return 'coordinateSchema'
    if ref in ("Page.FrameId", "Accessibility.AXNodeId"):
        return 'map[string]any{"type": "string"}'
    if ref in types_by_id:
        t = types_by_id[ref]
        if t.get("type") == "string" and "enum" in t:
            vals = [f'"{v}"' for v in t["enum"]]
            return f'map[string]any{{"type": "string", "enum": []string{{{", ".join(vals)}}}}}'
        return f'map[string]any{{"type": "{TYPE_MAP.get(t.get("type", "string"), "string")}"}}'
    return 'map[string]any{"type": "string"}'


def param_to_schema(param, types_by_id):
    """Convert a CDP parameter to a Go JSON Schema map literal."""
    desc = param.get("description", "").replace('"', '\\"').replace("\n", " ").strip()
    if len(desc) > 120:
        desc = desc[:117] + "..."

    if "$ref" in param:
        ref = param["$ref"]
        if ref == "Selector":
            return "selectorSchema"
        if ref == "Coordinate":
            return "coordinateSchema"
        base = ref_to_schema(ref, types_by_id)
        if desc:
            return f'withDesc({base}, "{desc}")'
        return base

    ptype = TYPE_MAP.get(param.get("type", "string"), "string")
    if desc:
        return f'map[string]any{{"type": "{ptype}", "description": "{desc}"}}'
    return f'map[string]any{{"type": "{ptype}"}}'


def generate(protocol_path):
    with open(protocol_path) as f:
        proto = json.load(f)

    antibot = None
    for domain in proto["domains"]:
        if domain["domain"] == "Antibot":
            antibot = domain
            break

    if not antibot:
        print("ERROR: Antibot domain not found in protocol", file=sys.stderr)
        sys.exit(1)

    types_by_id = {}
    for t in antibot.get("types", []):
        types_by_id[t["id"]] = t

    lines = []
    lines.append('// Code generated by gen_antibot_schemas.py from browser_protocol.json. DO NOT EDIT.')
    lines.append('')
    lines.append('package scrapflyprovider')
    lines.append('')

    # Shared schemas
    lines.append('// selectorSchema is the JSON Schema for the Antibot Selector type.')
    lines.append('var selectorSchema = map[string]any{')
    lines.append('\t"type": "object",')
    lines.append('\t"description": "Element selector. Use {type:\\"axNodeId\\", query:\\"<id>\\"} with the id from cloud_browser_snapshot (preferred). Also supports css, xpath, role, coord.",')
    lines.append('\t"properties": map[string]any{')
    lines.append('\t\t"type": map[string]any{')
    lines.append('\t\t\t"type": "string",')
    lines.append('\t\t\t"enum": []string{"axNodeId", "css", "xpath", "role", "coord"},')
    lines.append('\t\t\t"description": "Selector type. Use axNodeId with id from snapshot (most reliable).",')
    lines.append('\t\t},')
    lines.append('\t\t"query": map[string]any{')
    lines.append('\t\t\t"type": "string",')
    lines.append('\t\t\t"description": "For axNodeId: the id from snapshot (e.g. 28). For css: CSS selector. For xpath: XPath. For coord: x,y.",')
    lines.append('\t\t},')
    lines.append('\t},')
    lines.append('\t"required": []string{"type", "query"},')
    lines.append('}')
    lines.append('')

    lines.append('var coordinateSchema = map[string]any{')
    lines.append('\t"type": "object",')
    lines.append('\t"properties": map[string]any{')
    lines.append('\t\t"x": map[string]any{"type": "number"},')
    lines.append('\t\t"y": map[string]any{"type": "number"},')
    lines.append('\t},')
    lines.append('}')
    lines.append('')

    lines.append('func withDesc(schema map[string]any, desc string) map[string]any {')
    lines.append('\tcopy := make(map[string]any, len(schema)+1)')
    lines.append('\tfor k, v := range schema {')
    lines.append('\t\tcopy[k] = v')
    lines.append('\t}')
    lines.append('\tcopy["description"] = desc')
    lines.append('\treturn copy')
    lines.append('}')
    lines.append('')

    # Generate schemas for each WebMCP command
    lines.append('// antibotToolSchemas maps Antibot CDP command names to MCP tool schema overrides.')
    lines.append('// Generated from the Antibot domain in browser_protocol.json.')
    lines.append('var antibotToolSchemas = map[string]antibotToolOverride{')

    for cmd in antibot.get("commands", []):
        name = cmd["name"]
        if name not in WEBMCP_COMMANDS:
            continue

        params = cmd.get("parameters", [])
        desc = cmd.get("description", "").replace('"', '\\"').replace("\n", " ").strip()
        if len(desc) > 200:
            desc = desc[:197] + "..."

        # Add axNodeId hint for commands that take selectors
        has_selector = any(p.get("$ref") == "Selector" for p in params)
        if has_selector:
            desc += " Use cloud_browser_snapshot to find elements, then target with {type: axNodeId, query: <id>}."

        lines.append(f'\t"{name}": {{')
        lines.append(f'\t\tdescription: "{desc}",')

        if not params:
            lines.append('\t\tschema: map[string]any{"type": "object", "properties": map[string]any{}},')
        else:
            lines.append('\t\tschema: map[string]any{')
            lines.append('\t\t\t"type": "object",')
            lines.append('\t\t\t"properties": map[string]any{')
            required = []
            for p in params:
                pname = p["name"]
                pschema = param_to_schema(p, types_by_id)
                lines.append(f'\t\t\t\t"{pname}": {pschema},')
                if not p.get("optional"):
                    required.append(f'"{pname}"')
            lines.append('\t\t\t},')
            if required:
                lines.append(f'\t\t\t"required": []string{{{", ".join(required)}}},')
            lines.append('\t\t},')

        lines.append('\t},')

    lines.append('}')
    return "\n".join(lines)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <browser_protocol.json>", file=sys.stderr)
        sys.exit(1)
    print(generate(sys.argv[1]))
